// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { CircleAPI } from './circle-api';
import { CircleDB } from './circle-db';

@Injectable({
  providedIn: 'root'
})
export class CircleService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  CircleServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private circlesUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gongsvg/go/v1/circles';

  constructor(
    private http: HttpClient
  ) { }

  /** GET circles from the server */
  getCircles(): Observable<CircleDB[]> {
    return this.http.get<CircleDB[]>(this.circlesUrl)
      .pipe(
        tap(_ => this.log('fetched circles')),
        catchError(this.handleError<CircleDB[]>('getCircles', []))
      );
  }

  /** GET circle by id. Will 404 if id not found */
  getCircle(id: number): Observable<CircleDB> {
    const url = `${this.circlesUrl}/${id}`;
    return this.http.get<CircleDB>(url).pipe(
      tap(_ => this.log(`fetched circle id=${id}`)),
      catchError(this.handleError<CircleDB>(`getCircle id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new circle to the server */
  postCircle(circledb: CircleDB): Observable<CircleDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    circledb.CircleAnimations = []
    let _SVG_Circles_reverse = circledb.SVG_Circles_reverse
    circledb.SVG_Circles_reverse = {}

		return this.http.post<CircleDB>(this.circlesUrl, circledb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
        circledb.SVG_Circles_reverse = _SVG_Circles_reverse
				this.log(`posted circledb id=${circledb.ID}`)
			}),
			catchError(this.handleError<CircleDB>('postCircle'))
		);
  }

  /** DELETE: delete the circledb from the server */
  deleteCircle(circledb: CircleDB | number): Observable<CircleDB> {
    const id = typeof circledb === 'number' ? circledb : circledb.ID;
    const url = `${this.circlesUrl}/${id}`;

    return this.http.delete<CircleDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted circledb id=${id}`)),
      catchError(this.handleError<CircleDB>('deleteCircle'))
    );
  }

  /** PUT: update the circledb on the server */
  updateCircle(circledb: CircleDB): Observable<CircleDB> {
    const id = typeof circledb === 'number' ? circledb : circledb.ID;
    const url = `${this.circlesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    circledb.CircleAnimations = []
    let _SVG_Circles_reverse = circledb.SVG_Circles_reverse
    circledb.SVG_Circles_reverse = {}

    return this.http.put(url, circledb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        circledb.SVG_Circles_reverse = _SVG_Circles_reverse
        this.log(`updated circledb id=${circledb.ID}`)
      }),
      catchError(this.handleError<CircleDB>('updateCircle'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
