// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { LineAPI } from './line-api';
import { LineDB } from './line-db';

@Injectable({
  providedIn: 'root'
})
export class LineService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  LineServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private linesUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gongsvg/go/v1/lines';

  constructor(
    private http: HttpClient
  ) { }

  /** GET lines from the server */
  getLines(): Observable<LineDB[]> {
    return this.http.get<LineDB[]>(this.linesUrl)
      .pipe(
        tap(_ => this.log('fetched lines')),
        catchError(this.handleError<LineDB[]>('getLines', []))
      );
  }

  /** GET line by id. Will 404 if id not found */
  getLine(id: number): Observable<LineDB> {
    const url = `${this.linesUrl}/${id}`;
    return this.http.get<LineDB>(url).pipe(
      tap(_ => this.log(`fetched line id=${id}`)),
      catchError(this.handleError<LineDB>(`getLine id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new line to the server */
  postLine(linedb: LineDB): Observable<LineDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    linedb.Animates = []
    let _SVG_Lines_reverse = linedb.SVG_Lines_reverse
    linedb.SVG_Lines_reverse = {}

		return this.http.post<LineDB>(this.linesUrl, linedb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
        linedb.SVG_Lines_reverse = _SVG_Lines_reverse
				this.log(`posted linedb id=${linedb.ID}`)
			}),
			catchError(this.handleError<LineDB>('postLine'))
		);
  }

  /** DELETE: delete the linedb from the server */
  deleteLine(linedb: LineDB | number): Observable<LineDB> {
    const id = typeof linedb === 'number' ? linedb : linedb.ID;
    const url = `${this.linesUrl}/${id}`;

    return this.http.delete<LineDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted linedb id=${id}`)),
      catchError(this.handleError<LineDB>('deleteLine'))
    );
  }

  /** PUT: update the linedb on the server */
  updateLine(linedb: LineDB): Observable<LineDB> {
    const id = typeof linedb === 'number' ? linedb : linedb.ID;
    const url = `${this.linesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    linedb.Animates = []
    let _SVG_Lines_reverse = linedb.SVG_Lines_reverse
    linedb.SVG_Lines_reverse = {}

    return this.http.put(url, linedb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        linedb.SVG_Lines_reverse = _SVG_Lines_reverse
        this.log(`updated linedb id=${linedb.ID}`)
      }),
      catchError(this.handleError<LineDB>('updateLine'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
