// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { SVGAPI } from './svg-api';
import { SVGDB } from './svg-db';

@Injectable({
  providedIn: 'root'
})
export class SVGService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  SVGServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private svgsUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gongsvg/go/v1/svgs';

  constructor(
    private http: HttpClient
  ) { }

  /** GET svgs from the server */
  getSVGs(): Observable<SVGDB[]> {
    return this.http.get<SVGDB[]>(this.svgsUrl)
      .pipe(
        tap(_ => this.log('fetched svgs')),
        catchError(this.handleError<SVGDB[]>('getSVGs', []))
      );
  }

  /** GET svg by id. Will 404 if id not found */
  getSVG(id: number): Observable<SVGDB> {
    const url = `${this.svgsUrl}/${id}`;
    return this.http.get<SVGDB>(url).pipe(
      tap(_ => this.log(`fetched svg id=${id}`)),
      catchError(this.handleError<SVGDB>(`getSVG id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new svg to the server */
  postSVG(svgdb: SVGDB): Observable<SVGDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    svgdb.Rects = []
    svgdb.Texts = []
    svgdb.Circles = []
    svgdb.Lines = []
    svgdb.Ellipses = []
    svgdb.Polylines = []
    svgdb.Polygones = []
    svgdb.Paths = []

		return this.http.post<SVGDB>(this.svgsUrl, svgdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted svgdb id=${svgdb.ID}`)
			}),
			catchError(this.handleError<SVGDB>('postSVG'))
		);
  }

  /** DELETE: delete the svgdb from the server */
  deleteSVG(svgdb: SVGDB | number): Observable<SVGDB> {
    const id = typeof svgdb === 'number' ? svgdb : svgdb.ID;
    const url = `${this.svgsUrl}/${id}`;

    return this.http.delete<SVGDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted svgdb id=${id}`)),
      catchError(this.handleError<SVGDB>('deleteSVG'))
    );
  }

  /** PUT: update the svgdb on the server */
  updateSVG(svgdb: SVGDB): Observable<SVGDB> {
    const id = typeof svgdb === 'number' ? svgdb : svgdb.ID;
    const url = `${this.svgsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    svgdb.Rects = []
    svgdb.Texts = []
    svgdb.Circles = []
    svgdb.Lines = []
    svgdb.Ellipses = []
    svgdb.Polylines = []
    svgdb.Polygones = []
    svgdb.Paths = []

    return this.http.put(url, svgdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated svgdb id=${svgdb.ID}`)
      }),
      catchError(this.handleError<SVGDB>('updateSVG'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
