// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { TextDB } from './text-db';

@Injectable({
  providedIn: 'root'
})
export class TextService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  TextServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private textsUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gongsvg/go/v1/texts';

  constructor(
    private http: HttpClient
  ) { }

  /** GET texts from the server */
  getTexts(): Observable<TextDB[]> {
    return this.http.get<TextDB[]>(this.textsUrl)
      .pipe(
        tap(_ => this.log('fetched texts')),
        catchError(this.handleError<TextDB[]>('getTexts', []))
      );
  }

  /** GET text by id. Will 404 if id not found */
  getText(id: number): Observable<TextDB> {
    const url = `${this.textsUrl}/${id}`;
    return this.http.get<TextDB>(url).pipe(
      tap(_ => this.log(`fetched text id=${id}`)),
      catchError(this.handleError<TextDB>(`getText id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new text to the server */
  postText(textdb: TextDB): Observable<TextDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    textdb.Animates = []
    let _SVG_Texts_reverse = textdb.SVG_Texts_reverse
    textdb.SVG_Texts_reverse = {}

		return this.http.post<TextDB>(this.textsUrl, textdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
        textdb.SVG_Texts_reverse = _SVG_Texts_reverse
				this.log(`posted textdb id=${textdb.ID}`)
			}),
			catchError(this.handleError<TextDB>('postText'))
		);
  }

  /** DELETE: delete the textdb from the server */
  deleteText(textdb: TextDB | number): Observable<TextDB> {
    const id = typeof textdb === 'number' ? textdb : textdb.ID;
    const url = `${this.textsUrl}/${id}`;

    return this.http.delete<TextDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted textdb id=${id}`)),
      catchError(this.handleError<TextDB>('deleteText'))
    );
  }

  /** PUT: update the textdb on the server */
  updateText(textdb: TextDB): Observable<TextDB> {
    const id = typeof textdb === 'number' ? textdb : textdb.ID;
    const url = `${this.textsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    textdb.Animates = []
    let _SVG_Texts_reverse = textdb.SVG_Texts_reverse
    textdb.SVG_Texts_reverse = {}

    return this.http.put(url, textdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        textdb.SVG_Texts_reverse = _SVG_Texts_reverse
        this.log(`updated textdb id=${textdb.ID}`)
      }),
      catchError(this.handleError<TextDB>('updateText'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
