// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { RectDB } from '../rect-db'
import { RectService } from '../rect.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-rectstable',
  templateUrl: './rects-table.component.html',
  styleUrls: ['./rects-table.component.css'],
})
export class RectsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of Rect instances
  selection: SelectionModel<RectDB>;
  initialSelection = new Array<RectDB>();

  // the data source for the table
  rects: RectDB[];
  matTableDataSource: MatTableDataSource<RectDB>

  // front repo, that will be referenced by this.rects
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (rectDB: RectDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return rectDB.Name;

        case 'X':
          return rectDB.X;

        case 'Y':
          return rectDB.Y;

        case 'Width':
          return rectDB.Width;

        case 'Height':
          return rectDB.Height;

        case 'RX':
          return rectDB.RX;

        case 'Color':
          return rectDB.Color;

        case 'FillOpacity':
          return rectDB.FillOpacity;

        case 'Stroke':
          return rectDB.Stroke;

        case 'StrokeWidth':
          return rectDB.StrokeWidth;

        case 'StrokeDashArray':
          return rectDB.StrokeDashArray;

        case 'Transform':
          return rectDB.Transform;

        case 'Rects':
          return this.frontRepo.SVGs.get(rectDB.SVG_RectsDBID.Int64)?.Name;

        default:
          return RectDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (rectDB: RectDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the rectDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += rectDB.Name.toLowerCase()
      mergedContent += rectDB.X.toString()
      mergedContent += rectDB.Y.toString()
      mergedContent += rectDB.Width.toString()
      mergedContent += rectDB.Height.toString()
      mergedContent += rectDB.RX.toString()
      mergedContent += rectDB.Color.toLowerCase()
      mergedContent += rectDB.FillOpacity.toString()
      mergedContent += rectDB.Stroke.toLowerCase()
      mergedContent += rectDB.StrokeWidth.toString()
      mergedContent += rectDB.StrokeDashArray.toLowerCase()
      mergedContent += rectDB.Transform.toLowerCase()
      if (rectDB.SVG_RectsDBID.Int64 != 0) {
        mergedContent += this.frontRepo.SVGs.get(rectDB.SVG_RectsDBID.Int64)?.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private rectService: RectService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of rect instances
    public dialogRef: MatDialogRef<RectsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.rectService.RectServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getRects()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "X",
        "Y",
        "Width",
        "Height",
        "RX",
        "Color",
        "FillOpacity",
        "Stroke",
        "StrokeWidth",
        "StrokeDashArray",
        "Transform",
        "Rects",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "X",
        "Y",
        "Width",
        "Height",
        "RX",
        "Color",
        "FillOpacity",
        "Stroke",
        "StrokeWidth",
        "StrokeDashArray",
        "Transform",
        "Rects",
      ]
      this.selection = new SelectionModel<RectDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getRects()
    this.matTableDataSource = new MatTableDataSource(this.rects)
  }

  getRects(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.rects = this.frontRepo.Rects_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.rects.forEach(
            rect => {
              let ID = this.dialogData.ID
              let revPointer = rect[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(rect)
              }
            }
          )
          this.selection = new SelectionModel<RectDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let rect = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(rect)
            }
          }
          this.selection = new SelectionModel<RectDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.rects
      }
    )
  }

  // newRect initiate a new rect
  // create a new Rect objet
  newRect() {
  }

  deleteRect(rectID: number, rect: RectDB) {
    // list of rects is truncated of rect before the delete
    this.rects = this.rects.filter(h => h !== rect);

    this.rectService.deleteRect(rectID).subscribe(
      rect => {
        this.rectService.RectServiceChanged.next("delete")
      }
    );
  }

  editRect(rectID: number, rect: RectDB) {

  }

  // display rect in router
  displayRectInRouter(rectID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongsvg_go-" + "rect-display", rectID])
  }

  // set editor outlet
  setEditorRouterOutlet(rectID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongsvg_go_editor: ["github_com_fullstack_lang_gongsvg_go-" + "rect-detail", rectID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(rectID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongsvg_go_presentation: ["github_com_fullstack_lang_gongsvg_go-" + "rect-presentation", rectID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.rects.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.rects.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<RectDB>()

      // reset all initial selection of rect that belong to rect
      this.initialSelection.forEach(
        rect => {
          rect[this.dialogData.ReversePointer].Int64 = 0
          rect[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(rect)
        }
      )

      // from selection, set rect that belong to rect
      this.selection.selected.forEach(
        rect => {
          let ID = +this.dialogData.ID
          rect[this.dialogData.ReversePointer].Int64 = ID
          rect[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(rect)
        }
      )

      // update all rect (only update selection & initial selection)
      toUpdate.forEach(
        rect => {
          this.rectService.updateRect(rect)
            .subscribe(rect => {
              this.rectService.RectServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedRect = new Set<number>()
      for (let rect of this.initialSelection) {
        if (this.selection.selected.includes(rect)) {
          // console.log("rect " + rect.Name + " is still selected")
        } else {
          console.log("rect " + rect.Name + " has been unselected")
          unselectedRect.add(rect.ID)
          console.log("is unselected " + unselectedRect.has(rect.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let rect = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedRect.has(rect.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          rect => {
            if (!this.initialSelection.includes(rect)) {
              // console.log("rect " + rect.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + rect.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = rect.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("rect " + rect.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<RectDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
