// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { EllipseDB } from '../ellipse-db'
import { EllipseService } from '../ellipse.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-ellipses-table',
  templateUrl: './ellipses-table.component.html',
  styleUrls: ['./ellipses-table.component.css'],
})
export class EllipsesTableComponent implements OnInit {

  // used if the component is called as a selection component of Ellipse instances
  selection: SelectionModel<EllipseDB>;
  initialSelection = new Array<EllipseDB>();

  // the data source for the table
  ellipses: EllipseDB[];
  matTableDataSource: MatTableDataSource<EllipseDB>


  // front repo, that will be referenced by this.ellipses
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private ellipseService: EllipseService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of ellipse instances
    public dialogRef: MatDialogRef<EllipsesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
    // this is for routerLink on same component when only queryParameter changes
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };

    // observable for changes in structs
    this.ellipseService.EllipseServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getEllipses()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "CX",
        "CY",
        "RX",
        "RY",
        "Color",
        "FillOpacity",
        "Stroke",
        "StrokeWidth",
        "StrokeDashArray",
        "Ellipses",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "CX",
        "CY",
        "RX",
        "RY",
        "Color",
        "FillOpacity",
        "Stroke",
        "StrokeWidth",
        "StrokeDashArray",
        "Ellipses",
      ]
      this.selection = new SelectionModel<EllipseDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getEllipses()
    this.matTableDataSource = new MatTableDataSource(this.ellipses)
  }

  getEllipses(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo
        console.log("front repo pull returned")

        this.ellipses = this.frontRepo.Ellipses_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.ellipses.forEach(
            ellipse => {
              let ID = this.dialogData.ID
              let revPointer = ellipse[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(ellipse)
              }
            }
          )
          this.selection = new SelectionModel<EllipseDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.ellipses
      }
    )
  }

  // newEllipse initiate a new ellipse
  // create a new Ellipse objet
  newEllipse() {
  }

  deleteEllipse(ellipseID: number, ellipse: EllipseDB) {
    // list of ellipses is truncated of ellipse before the delete
    this.ellipses = this.ellipses.filter(h => h !== ellipse);

    this.ellipseService.deleteEllipse(ellipseID).subscribe(
      ellipse => {
        this.ellipseService.EllipseServiceChanged.next("delete")

        console.log("ellipse deleted")
      }
    );
  }

  editEllipse(ellipseID: number, ellipse: EllipseDB) {

  }

  // display ellipse in router
  displayEllipseInRouter(ellipseID: number) {
    this.router.navigate(["ellipse-display", ellipseID])
  }

  // set editor outlet
  setEditorRouterOutlet(ellipseID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["ellipse-detail", ellipseID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(ellipseID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["ellipse-presentation", ellipseID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.ellipses.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.ellipses.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<EllipseDB>()

    // reset all initial selection of ellipse that belong to ellipse through Anarrayofb
    this.initialSelection.forEach(
      ellipse => {
        ellipse[this.dialogData.ReversePointer].Int64 = 0
        ellipse[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(ellipse)
      }
    )

    // from selection, set ellipse that belong to ellipse through Anarrayofb
    this.selection.selected.forEach(
      ellipse => {
        console.log("selection ID " + ellipse.ID)
        let ID = +this.dialogData.ID
        ellipse[this.dialogData.ReversePointer].Int64 = ID
        ellipse[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(ellipse)
      }
    )

    // update all ellipse (only update selection & initial selection)
    toUpdate.forEach(
      ellipse => {
        this.ellipseService.updateEllipse(ellipse)
          .subscribe(ellipse => {
            this.ellipseService.EllipseServiceChanged.next("update")
            console.log("ellipse saved")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
