// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"net/http"
	"time"

	"github.com/fullstack-lang/gongsvg/go/models"
	"github.com/fullstack-lang/gongsvg/go/orm"

	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
)

// declaration in order to justify use of the models import
var __Polyline__dummysDeclaration__ models.Polyline
var __Polyline_time__dummyDeclaration time.Duration

// An PolylineID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getPolyline updatePolyline deletePolyline
type PolylineID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// PolylineInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postPolyline updatePolyline
type PolylineInput struct {
	// The Polyline to submit or modify
	// in: body
	Polyline *orm.PolylineAPI
}

// GetPolylines
//
// swagger:route GET /polylines polylines getPolylines
//
// Get all polylines
//
// Responses:
//    default: genericError
//        200: polylineDBsResponse
func GetPolylines(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	var polylines []orm.PolylineDB
	query := db.Find(&polylines)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// for each polyline, update fields from the database nullable fields
	for idx := range polylines {
		polyline := &polylines[idx]
		_ = polyline
		// insertion point for updating fields
		if polyline.Name_Data.Valid {
			polyline.Name = polyline.Name_Data.String
		}

		if polyline.Points_Data.Valid {
			polyline.Points = polyline.Points_Data.String
		}

		if polyline.Color_Data.Valid {
			polyline.Color = polyline.Color_Data.String
		}

		if polyline.FillOpacity_Data.Valid {
			polyline.FillOpacity = polyline.FillOpacity_Data.Float64
		}

		if polyline.Stroke_Data.Valid {
			polyline.Stroke = polyline.Stroke_Data.String
		}

		if polyline.StrokeWidth_Data.Valid {
			polyline.StrokeWidth = polyline.StrokeWidth_Data.Float64
		}

		if polyline.StrokeDashArray_Data.Valid {
			polyline.StrokeDashArray = polyline.StrokeDashArray_Data.String
		}

	}

	c.JSON(http.StatusOK, polylines)
}

// PostPolyline
//
// swagger:route POST /polylines polylines postPolyline
//
// Creates a polyline
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//     Responses:
//       200: polylineDBResponse
func PostPolyline(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Validate input
	var input orm.PolylineAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create polyline
	polylineDB := orm.PolylineDB{}
	polylineDB.PolylineAPI = input
	// insertion point for nullable field set
	polylineDB.Name_Data.String = input.Name
	polylineDB.Name_Data.Valid = true

	polylineDB.Points_Data.String = input.Points
	polylineDB.Points_Data.Valid = true

	polylineDB.Color_Data.String = input.Color
	polylineDB.Color_Data.Valid = true

	polylineDB.FillOpacity_Data.Float64 = input.FillOpacity
	polylineDB.FillOpacity_Data.Valid = true

	polylineDB.Stroke_Data.String = input.Stroke
	polylineDB.Stroke_Data.Valid = true

	polylineDB.StrokeWidth_Data.Float64 = input.StrokeWidth
	polylineDB.StrokeWidth_Data.Valid = true

	polylineDB.StrokeDashArray_Data.String = input.StrokeDashArray
	polylineDB.StrokeDashArray_Data.Valid = true

	query := db.Create(&polylineDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	c.JSON(http.StatusOK, polylineDB)
}

// GetPolyline
//
// swagger:route GET /polylines/{ID} polylines getPolyline
//
// Gets the details for a polyline.
//
// Responses:
//    default: genericError
//        200: polylineDBResponse
func GetPolyline(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get polyline in DB
	var polyline orm.PolylineDB
	if err := db.First(&polyline, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// insertion point for fields value set from nullable fields
	if polyline.Name_Data.Valid {
		polyline.Name = polyline.Name_Data.String
	}

	if polyline.Points_Data.Valid {
		polyline.Points = polyline.Points_Data.String
	}

	if polyline.Color_Data.Valid {
		polyline.Color = polyline.Color_Data.String
	}

	if polyline.FillOpacity_Data.Valid {
		polyline.FillOpacity = polyline.FillOpacity_Data.Float64
	}

	if polyline.Stroke_Data.Valid {
		polyline.Stroke = polyline.Stroke_Data.String
	}

	if polyline.StrokeWidth_Data.Valid {
		polyline.StrokeWidth = polyline.StrokeWidth_Data.Float64
	}

	if polyline.StrokeDashArray_Data.Valid {
		polyline.StrokeDashArray = polyline.StrokeDashArray_Data.String
	}

	c.JSON(http.StatusOK, polyline)
}

// UpdatePolyline
//
// swagger:route PATCH /polylines/{ID} polylines updatePolyline
//
// Update a polyline
//
// Responses:
//    default: genericError
//        200: polylineDBResponse
func UpdatePolyline(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var polylineDB orm.PolylineDB

	// fetch the polyline
	query := db.First(&polylineDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.PolylineAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	// insertion point for nullable field set
	input.Name_Data.String = input.Name
	input.Name_Data.Valid = true

	input.Points_Data.String = input.Points
	input.Points_Data.Valid = true

	input.Color_Data.String = input.Color
	input.Color_Data.Valid = true

	input.FillOpacity_Data.Float64 = input.FillOpacity
	input.FillOpacity_Data.Valid = true

	input.Stroke_Data.String = input.Stroke
	input.Stroke_Data.Valid = true

	input.StrokeWidth_Data.Float64 = input.StrokeWidth
	input.StrokeWidth_Data.Valid = true

	input.StrokeDashArray_Data.String = input.StrokeDashArray
	input.StrokeDashArray_Data.Valid = true

	query = db.Model(&polylineDB).Updates(input)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	// return status OK with the marshalling of the the polylineDB
	c.JSON(http.StatusOK, polylineDB)
}

// DeletePolyline
//
// swagger:route DELETE /polylines/{ID} polylines deletePolyline
//
// Delete a polyline
//
// Responses:
//    default: genericError
func DeletePolyline(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var polylineDB orm.PolylineDB
	if err := db.First(&polylineDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&polylineDB)

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
