// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { PathDB } from '../path-db'
import { PathService } from '../path.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-paths-table',
  templateUrl: './paths-table.component.html',
  styleUrls: ['./paths-table.component.css'],
})
export class PathsTableComponent implements OnInit {

  // used if the component is called as a selection component of Path instances
  selection: SelectionModel<PathDB>;
  initialSelection = new Array<PathDB>();

  // the data source for the table
  paths: PathDB[];
  matTableDataSource: MatTableDataSource<PathDB>


  // front repo, that will be referenced by this.paths
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private pathService: PathService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of path instances
    public dialogRef: MatDialogRef<PathsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.pathService.PathServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getPaths()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Definition",
        "Color",
        "FillOpacity",
        "Stroke",
        "StrokeWidth",
        "StrokeDashArray",
        "Transform",
        "Paths",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Definition",
        "Color",
        "FillOpacity",
        "Stroke",
        "StrokeWidth",
        "StrokeDashArray",
        "Transform",
        "Paths",
      ]
      this.selection = new SelectionModel<PathDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getPaths()
    this.matTableDataSource = new MatTableDataSource(this.paths)
  }

  getPaths(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.paths = this.frontRepo.Paths_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.paths.forEach(
            path => {
              let ID = this.dialogData.ID
              let revPointer = path[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(path)
              }
            }
          )
          this.selection = new SelectionModel<PathDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.paths
      }
    )
  }

  // newPath initiate a new path
  // create a new Path objet
  newPath() {
  }

  deletePath(pathID: number, path: PathDB) {
    // list of paths is truncated of path before the delete
    this.paths = this.paths.filter(h => h !== path);

    this.pathService.deletePath(pathID).subscribe(
      path => {
        this.pathService.PathServiceChanged.next("delete")
      }
    );
  }

  editPath(pathID: number, path: PathDB) {

  }

  // display path in router
  displayPathInRouter(pathID: number) {
    this.router.navigate(["path-display", pathID])
  }

  // set editor outlet
  setEditorRouterOutlet(pathID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["path-detail", pathID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(pathID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["path-presentation", pathID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.paths.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.paths.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<PathDB>()

    // reset all initial selection of path that belong to path through Anarrayofb
    this.initialSelection.forEach(
      path => {
        path[this.dialogData.ReversePointer].Int64 = 0
        path[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(path)
      }
    )

    // from selection, set path that belong to path through Anarrayofb
    this.selection.selected.forEach(
      path => {
        let ID = +this.dialogData.ID
        path[this.dialogData.ReversePointer].Int64 = ID
        path[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(path)
      }
    )

    // update all path (only update selection & initial selection)
    toUpdate.forEach(
      path => {
        this.pathService.updatePath(path)
          .subscribe(path => {
            this.pathService.PathServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
