// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { TextDB } from '../text-db'
import { TextService } from '../text.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-texts-table',
  templateUrl: './texts-table.component.html',
  styleUrls: ['./texts-table.component.css'],
})
export class TextsTableComponent implements OnInit {

  // used if the component is called as a selection component of Text instances
  selection: SelectionModel<TextDB>;
  initialSelection = new Array<TextDB>();

  // the data source for the table
  texts: TextDB[];
  matTableDataSource: MatTableDataSource<TextDB>


  // front repo, that will be referenced by this.texts
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private textService: TextService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of text instances
    public dialogRef: MatDialogRef<TextsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.textService.TextServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getTexts()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "X",
        "Y",
        "Content",
        "Color",
        "FillOpacity",
        "Stroke",
        "StrokeWidth",
        "StrokeDashArray",
        "Transform",
        "Texts",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "X",
        "Y",
        "Content",
        "Color",
        "FillOpacity",
        "Stroke",
        "StrokeWidth",
        "StrokeDashArray",
        "Transform",
        "Texts",
      ]
      this.selection = new SelectionModel<TextDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getTexts()
    this.matTableDataSource = new MatTableDataSource(this.texts)
  }

  getTexts(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.texts = this.frontRepo.Texts_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.texts.forEach(
            text => {
              let ID = this.dialogData.ID
              let revPointer = text[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(text)
              }
            }
          )
          this.selection = new SelectionModel<TextDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.texts
      }
    )
  }

  // newText initiate a new text
  // create a new Text objet
  newText() {
  }

  deleteText(textID: number, text: TextDB) {
    // list of texts is truncated of text before the delete
    this.texts = this.texts.filter(h => h !== text);

    this.textService.deleteText(textID).subscribe(
      text => {
        this.textService.TextServiceChanged.next("delete")
      }
    );
  }

  editText(textID: number, text: TextDB) {

  }

  // display text in router
  displayTextInRouter(textID: number) {
    this.router.navigate(["text-display", textID])
  }

  // set editor outlet
  setEditorRouterOutlet(textID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["text-detail", textID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(textID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["text-presentation", textID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.texts.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.texts.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<TextDB>()

    // reset all initial selection of text that belong to text through Anarrayofb
    this.initialSelection.forEach(
      text => {
        text[this.dialogData.ReversePointer].Int64 = 0
        text[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(text)
      }
    )

    // from selection, set text that belong to text through Anarrayofb
    this.selection.selected.forEach(
      text => {
        let ID = +this.dialogData.ID
        text[this.dialogData.ReversePointer].Int64 = ID
        text[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(text)
      }
    )

    // update all text (only update selection & initial selection)
    toUpdate.forEach(
      text => {
        this.textService.updateText(text)
          .subscribe(text => {
            this.textService.TextServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
