// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { SVGDB } from '../svg-db'
import { SVGService } from '../svg.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-svg-sorting',
  templateUrl: './svg-sorting.component.html',
  styleUrls: ['./svg-sorting.component.css']
})
export class SVGSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of SVG instances that are in the association
  associatedSVGs = new Array<SVGDB>();

  constructor(
    private svgService: SVGService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of svg instances
    public dialogRef: MatDialogRef<SVGSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getSVGs()
  }

  getSVGs(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let svg of this.frontRepo.SVGs_array) {
          let ID = this.dialogData.ID
          let revPointerID = svg[this.dialogData.ReversePointer]
          let revPointerID_Index = svg[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedSVGs.push(svg)
          }
        }

        // sort associated svg according to order
        this.associatedSVGs.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });

        console.log("front repo pull returned")
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedSVGs, event.previousIndex, event.currentIndex);

    // set the order of SVG instances
    let index = 0
    
    for (let svg of this.associatedSVGs) {
      let revPointerID_Index = svg[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
    console.log("after drop")
  }

  save() {

    this.associatedSVGs.forEach(
      svg => {
        this.svgService.updateSVG(svg)
          .subscribe(svg => {
            this.svgService.SVGServiceChanged.next("update")
            console.log("svg saved")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
