// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { CircleDB } from '../circle-db'
import { CircleService } from '../circle.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-circles-table',
  templateUrl: './circles-table.component.html',
  styleUrls: ['./circles-table.component.css'],
})
export class CirclesTableComponent implements OnInit {

  // used if the component is called as a selection component of Circle instances
  selection: SelectionModel<CircleDB>;
  initialSelection = new Array<CircleDB>();

  // the data source for the table
  circles: CircleDB[];
  matTableDataSource: MatTableDataSource<CircleDB>


  // front repo, that will be referenced by this.circles
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private circleService: CircleService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of circle instances
    public dialogRef: MatDialogRef<CirclesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.circleService.CircleServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getCircles()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "CX",
        "CY",
        "Radius",
        "Color",
        "FillOpacity",
        "Stroke",
        "StrokeWidth",
        "StrokeDashArray",
        "Transform",
        "Circles",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "CX",
        "CY",
        "Radius",
        "Color",
        "FillOpacity",
        "Stroke",
        "StrokeWidth",
        "StrokeDashArray",
        "Transform",
        "Circles",
      ]
      this.selection = new SelectionModel<CircleDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getCircles()
    this.matTableDataSource = new MatTableDataSource(this.circles)
  }

  getCircles(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.circles = this.frontRepo.Circles_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.circles.forEach(
            circle => {
              let ID = this.dialogData.ID
              let revPointer = circle[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(circle)
              }
            }
          )
          this.selection = new SelectionModel<CircleDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.circles
      }
    )
  }

  // newCircle initiate a new circle
  // create a new Circle objet
  newCircle() {
  }

  deleteCircle(circleID: number, circle: CircleDB) {
    // list of circles is truncated of circle before the delete
    this.circles = this.circles.filter(h => h !== circle);

    this.circleService.deleteCircle(circleID).subscribe(
      circle => {
        this.circleService.CircleServiceChanged.next("delete")
      }
    );
  }

  editCircle(circleID: number, circle: CircleDB) {

  }

  // display circle in router
  displayCircleInRouter(circleID: number) {
    this.router.navigate(["circle-display", circleID])
  }

  // set editor outlet
  setEditorRouterOutlet(circleID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["circle-detail", circleID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(circleID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["circle-presentation", circleID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.circles.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.circles.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<CircleDB>()

    // reset all initial selection of circle that belong to circle through Anarrayofb
    this.initialSelection.forEach(
      circle => {
        circle[this.dialogData.ReversePointer].Int64 = 0
        circle[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(circle)
      }
    )

    // from selection, set circle that belong to circle through Anarrayofb
    this.selection.selected.forEach(
      circle => {
        let ID = +this.dialogData.ID
        circle[this.dialogData.ReversePointer].Int64 = ID
        circle[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(circle)
      }
    )

    // update all circle (only update selection & initial selection)
    toUpdate.forEach(
      circle => {
        this.circleService.updateCircle(circle)
          .subscribe(circle => {
            this.circleService.CircleServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
