// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { EllipseDB } from '../ellipse-db'
import { EllipseService } from '../ellipse.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-ellipse-sorting',
  templateUrl: './ellipse-sorting.component.html',
  styleUrls: ['./ellipse-sorting.component.css']
})
export class EllipseSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of Ellipse instances that are in the association
  associatedEllipses = new Array<EllipseDB>();

  constructor(
    private ellipseService: EllipseService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of ellipse instances
    public dialogRef: MatDialogRef<EllipseSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getEllipses()
  }

  getEllipses(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let ellipse of this.frontRepo.Ellipses_array) {
          let ID = this.dialogData.ID
          let revPointerID = ellipse[this.dialogData.ReversePointer]
          let revPointerID_Index = ellipse[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedEllipses.push(ellipse)
          }
        }

        // sort associated ellipse according to order
        this.associatedEllipses.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedEllipses, event.previousIndex, event.currentIndex);

    // set the order of Ellipse instances
    let index = 0
    
    for (let ellipse of this.associatedEllipses) {
      let revPointerID_Index = ellipse[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedEllipses.forEach(
      ellipse => {
        this.ellipseService.updateEllipse(ellipse)
          .subscribe(ellipse => {
            this.ellipseService.EllipseServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
